from dobot_msgs_v4.srv._acc_j import AccJ  # noqa: F401
from dobot_msgs_v4.srv._acc_l import AccL  # noqa: F401
from dobot_msgs_v4.srv._ai import AI  # noqa: F401
from dobot_msgs_v4.srv._ao import AO  # noqa: F401
from dobot_msgs_v4.srv._ao_instant import AOInstant  # noqa: F401
from dobot_msgs_v4.srv._arc import Arc  # noqa: F401
from dobot_msgs_v4.srv._brake_control import BrakeControl  # noqa: F401
from dobot_msgs_v4.srv._calc_tool import CalcTool  # noqa: F401
from dobot_msgs_v4.srv._calc_user import CalcUser  # noqa: F401
from dobot_msgs_v4.srv._check_odd_mov_c import CheckOddMovC  # noqa: F401
from dobot_msgs_v4.srv._check_odd_mov_j import CheckOddMovJ  # noqa: F401
from dobot_msgs_v4.srv._check_odd_mov_l import CheckOddMovL  # noqa: F401
from dobot_msgs_v4.srv._circle import Circle  # noqa: F401
from dobot_msgs_v4.srv._clear_error import ClearError  # noqa: F401
from dobot_msgs_v4.srv._continue import Continue  # noqa: F401
from dobot_msgs_v4.srv._cp import CP  # noqa: F401
from dobot_msgs_v4.srv._di import DI  # noqa: F401
from dobot_msgs_v4.srv._di_group import DIGroup  # noqa: F401
from dobot_msgs_v4.srv._di_group_dec import DIGroupDEC  # noqa: F401
from dobot_msgs_v4.srv._disable_robot import DisableRobot  # noqa: F401
from dobot_msgs_v4.srv._do import DO  # noqa: F401
from dobot_msgs_v4.srv._do_group import DOGroup  # noqa: F401
from dobot_msgs_v4.srv._do_group_dec import DOGroupDEC  # noqa: F401
from dobot_msgs_v4.srv._do_instant import DOInstant  # noqa: F401
from dobot_msgs_v4.srv._drag_sensivity import DragSensivity  # noqa: F401
from dobot_msgs_v4.srv._emergency_stop import EmergencyStop  # noqa: F401
from dobot_msgs_v4.srv._enable_ft_sensor import EnableFTSensor  # noqa: F401
from dobot_msgs_v4.srv._enable_robot import EnableRobot  # noqa: F401
from dobot_msgs_v4.srv._enable_safe_skin import EnableSafeSkin  # noqa: F401
from dobot_msgs_v4.srv._end_rt_offset import EndRTOffset  # noqa: F401
from dobot_msgs_v4.srv._fc_collision_switch import FCCollisionSwitch  # noqa: F401
from dobot_msgs_v4.srv._fc_force_mode import FCForceMode  # noqa: F401
from dobot_msgs_v4.srv._fc_off import FCOff  # noqa: F401
from dobot_msgs_v4.srv._fc_set_damping import FCSetDamping  # noqa: F401
from dobot_msgs_v4.srv._fc_set_deviation import FCSetDeviation  # noqa: F401
from dobot_msgs_v4.srv._fc_set_force import FCSetForce  # noqa: F401
from dobot_msgs_v4.srv._fc_set_force_limit import FCSetForceLimit  # noqa: F401
from dobot_msgs_v4.srv._fc_set_force_speed_limit import FCSetForceSpeedLimit  # noqa: F401
from dobot_msgs_v4.srv._fc_set_mass import FCSetMass  # noqa: F401
from dobot_msgs_v4.srv._fc_set_stiffness import FCSetStiffness  # noqa: F401
from dobot_msgs_v4.srv._force_drive_mode import ForceDriveMode  # noqa: F401
from dobot_msgs_v4.srv._force_drive_speed import ForceDriveSpeed  # noqa: F401
from dobot_msgs_v4.srv._get_angle import GetAngle  # noqa: F401
from dobot_msgs_v4.srv._get_ao import GetAO  # noqa: F401
from dobot_msgs_v4.srv._get_coils import GetCoils  # noqa: F401
from dobot_msgs_v4.srv._get_current_command_id import GetCurrentCommandId  # noqa: F401
from dobot_msgs_v4.srv._get_do import GetDO  # noqa: F401
from dobot_msgs_v4.srv._get_do_group import GetDOGroup  # noqa: F401
from dobot_msgs_v4.srv._get_do_group_dec import GetDOGroupDEC  # noqa: F401
from dobot_msgs_v4.srv._get_error import GetError  # noqa: F401
from dobot_msgs_v4.srv._get_error_id import GetErrorID  # noqa: F401
from dobot_msgs_v4.srv._get_force import GetForce  # noqa: F401
from dobot_msgs_v4.srv._get_hold_regs import GetHoldRegs  # noqa: F401
from dobot_msgs_v4.srv._get_in_bits import GetInBits  # noqa: F401
from dobot_msgs_v4.srv._get_in_regs import GetInRegs  # noqa: F401
from dobot_msgs_v4.srv._get_input_bool import GetInputBool  # noqa: F401
from dobot_msgs_v4.srv._get_input_float import GetInputFloat  # noqa: F401
from dobot_msgs_v4.srv._get_input_int import GetInputInt  # noqa: F401
from dobot_msgs_v4.srv._get_output_bool import GetOutputBool  # noqa: F401
from dobot_msgs_v4.srv._get_output_float import GetOutputFloat  # noqa: F401
from dobot_msgs_v4.srv._get_output_int import GetOutputInt  # noqa: F401
from dobot_msgs_v4.srv._get_pose import GetPose  # noqa: F401
from dobot_msgs_v4.srv._get_start_pose import GetStartPose  # noqa: F401
from dobot_msgs_v4.srv._get_tool_do import GetToolDO  # noqa: F401
from dobot_msgs_v4.srv._inverse_kin import InverseKin  # noqa: F401
from dobot_msgs_v4.srv._inverse_solution import InverseSolution  # noqa: F401
from dobot_msgs_v4.srv._modbus_close import ModbusClose  # noqa: F401
from dobot_msgs_v4.srv._modbus_create import ModbusCreate  # noqa: F401
from dobot_msgs_v4.srv._modbus_rtu_create import ModbusRTUCreate  # noqa: F401
from dobot_msgs_v4.srv._mov_j import MovJ  # noqa: F401
from dobot_msgs_v4.srv._mov_jio import MovJIO  # noqa: F401
from dobot_msgs_v4.srv._mov_l import MovL  # noqa: F401
from dobot_msgs_v4.srv._mov_lio import MovLIO  # noqa: F401
from dobot_msgs_v4.srv._move_jog import MoveJog  # noqa: F401
from dobot_msgs_v4.srv._pause import Pause  # noqa: F401
from dobot_msgs_v4.srv._positive_kin import PositiveKin  # noqa: F401
from dobot_msgs_v4.srv._power_on import PowerOn  # noqa: F401
from dobot_msgs_v4.srv._rel_joint_mov_j import RelJointMovJ  # noqa: F401
from dobot_msgs_v4.srv._rel_mov_j_tool import RelMovJTool  # noqa: F401
from dobot_msgs_v4.srv._rel_mov_j_user import RelMovJUser  # noqa: F401
from dobot_msgs_v4.srv._rel_mov_l_tool import RelMovLTool  # noqa: F401
from dobot_msgs_v4.srv._rel_mov_l_user import RelMovLUser  # noqa: F401
from dobot_msgs_v4.srv._request_control import RequestControl  # noqa: F401
from dobot_msgs_v4.srv._reset_robot import ResetRobot  # noqa: F401
from dobot_msgs_v4.srv._robot_mode import RobotMode  # noqa: F401
from dobot_msgs_v4.srv._run_script import RunScript  # noqa: F401
from dobot_msgs_v4.srv._run_to import RunTo  # noqa: F401
from dobot_msgs_v4.srv._servo_j import ServoJ  # noqa: F401
from dobot_msgs_v4.srv._servo_p import ServoP  # noqa: F401
from dobot_msgs_v4.srv._set_back_distance import SetBackDistance  # noqa: F401
from dobot_msgs_v4.srv._set_coils import SetCoils  # noqa: F401
from dobot_msgs_v4.srv._set_collision_level import SetCollisionLevel  # noqa: F401
from dobot_msgs_v4.srv._set_fc_collision import SetFCCollision  # noqa: F401
from dobot_msgs_v4.srv._set_hold_regs import SetHoldRegs  # noqa: F401
from dobot_msgs_v4.srv._set_output_bool import SetOutputBool  # noqa: F401
from dobot_msgs_v4.srv._set_output_float import SetOutputFloat  # noqa: F401
from dobot_msgs_v4.srv._set_output_int import SetOutputInt  # noqa: F401
from dobot_msgs_v4.srv._set_payload import SetPayload  # noqa: F401
from dobot_msgs_v4.srv._set_post_collision_mode import SetPostCollisionMode  # noqa: F401
from dobot_msgs_v4.srv._set_safe_skin import SetSafeSkin  # noqa: F401
from dobot_msgs_v4.srv._set_safe_wall_enable import SetSafeWallEnable  # noqa: F401
from dobot_msgs_v4.srv._set_tool import SetTool  # noqa: F401
from dobot_msgs_v4.srv._set_tool485 import SetTool485  # noqa: F401
from dobot_msgs_v4.srv._set_tool_mode import SetToolMode  # noqa: F401
from dobot_msgs_v4.srv._set_tool_power import SetToolPower  # noqa: F401
from dobot_msgs_v4.srv._set_user import SetUser  # noqa: F401
from dobot_msgs_v4.srv._set_work_zone_enable import SetWorkZoneEnable  # noqa: F401
from dobot_msgs_v4.srv._six_force_home import SixForceHome  # noqa: F401
from dobot_msgs_v4.srv._speed_factor import SpeedFactor  # noqa: F401
from dobot_msgs_v4.srv._start_drag import StartDrag  # noqa: F401
from dobot_msgs_v4.srv._start_path import StartPath  # noqa: F401
from dobot_msgs_v4.srv._start_rt_offset import StartRTOffset  # noqa: F401
from dobot_msgs_v4.srv._stop import Stop  # noqa: F401
from dobot_msgs_v4.srv._stop_drag import StopDrag  # noqa: F401
from dobot_msgs_v4.srv._stop_move_jog import StopMoveJog  # noqa: F401
from dobot_msgs_v4.srv._tcp_dashboard import TcpDashboard  # noqa: F401
from dobot_msgs_v4.srv._tool import Tool  # noqa: F401
from dobot_msgs_v4.srv._tool_ai import ToolAI  # noqa: F401
from dobot_msgs_v4.srv._tool_di import ToolDI  # noqa: F401
from dobot_msgs_v4.srv._tool_do import ToolDO  # noqa: F401
from dobot_msgs_v4.srv._tool_do_instant import ToolDOInstant  # noqa: F401
from dobot_msgs_v4.srv._user import User  # noqa: F401
from dobot_msgs_v4.srv._vel_j import VelJ  # noqa: F401
from dobot_msgs_v4.srv._vel_l import VelL  # noqa: F401
